Add Tauri system dependencies to CI (#1)
These packages are installed via `apt install`:
- libgtk-3-dev
- libsoup2.4-dev
- libjavascriptcoregtk-4.0-dev
- libwebkit2gtk-4.0-dev

These binaries are installed via `cargo install`:
- trunk
- tauri-cli

Update README install instructions

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -16,12 +16,17 @@ jobs:
       - name: Checkout sources
         uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791 # v2.5.0, 2022-10-13
 
-      - name: Install stable toolchain
+      - name: Install stable toolchain + additional wasm target
         uses: actions-rs/toolchain@b2417cde72dcf67f306c0ae8e0828a81bf0b189f # v1.0.7, 2020-03-24
         with:
+          target: wasm32-unknown-unknown
           profile: minimal
           toolchain: stable
           override: true
+
+      - name: Install Tauri system dependencies
+        run: |
+          sudo apt install -y libgtk-3-dev libsoup2.4-dev libjavascriptcoregtk-4.0-dev libwebkit2gtk-4.0-dev
 
       # We always build with latest stable, so we also reset
       # the CI cache when new versions of Rust are released.
@@ -31,11 +36,10 @@ jobs:
           RUST_VERSION=$(rustc -V | grep -Po '(?<=^rustc )\S+')
           echo "rustc-version=$RUST_VERSION" >> $GITHUB_OUTPUT
 
-      # 1. Use both `**/Cargo.lock` and `**/Cargo.toml` in cache key: While Cargo.lock is enough
-      #    to ensure that we clear the cache when dependencies change, we currently don't treat
-      #    forgetting to commit Cargo.lock as a failure; changing Cargo.toml without bumping the
-      #    dependencies may clear the cache when it isn't necessary.
-      # 2. Don't include target/ -- only cache building 3rd-party libraries.
+      # Use both `**/Cargo.lock` and `**/Cargo.toml` in cache key: While Cargo.lock is enough to
+      # ensure that we clear the cache when dependencies change, we currently don't treat forgetting
+      # to commit Cargo.lock as a failure. Changing Cargo.toml without bumping the dependencies may
+      # clear the cache when it isn't necessary.
       - name: Use build cache
         uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7 # v3.0.11, 2022-10-13
         with:
@@ -47,7 +51,24 @@ jobs:
             target/
           key: ${{ runner.os }}-cargo-${{ steps.vars.outputs.rustc-version }}-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
 
-      - name: cargo build
+      - name: Install trunk, tauri-cli
+        run: |
+          # if $1 isn't a callable program, install $2.
+          cargo_install_() {
+            if ! command -v $1 >/dev/null 2>&1; then
+              cargo install --locked $2
+            fi
+          }
+          cargo_install_ trunk trunk
+          cargo_install_ cargo-tauri tauri-cli
+
+      # Calling tauri.conf.json when building yew front-end ensures CI builds the same way as we do.
+      - name: Build yew front-end (trunk build)
+        run: |
+          # eval $(jq -r '.build.beforeDevCommand' src-tauri/tauri.conf.json)
+          cd frontend && trunk build --release
+
+      - name: Build tauri back-end (cargo build)
         run: cargo build --all-targets
 
       - name: cargo fmt
